### ISSUE TITLE
关掉kafka_tools后，再次打开之前的请求数据就不见了，是否可以考虑支持持久化一下？

### ISSUE THREAD

**Issue by kaitezhan** [hanhuafeng/kafka_tools#1]

**Comment by hanhuafeng** [comment]
这个可以考虑支持的，今天我实现一下

**Comment by hanhuafeng** [comment]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/40729245/212618339-9e880ecf-9c36-44e2-b6db-c6009891cbf6.png">

**Comment by hanhuafeng** [comment]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/40729245/212618449-3839ed11-290b-4c77-8cf1-6b9e59dcb771.png">

**Comment by hanhuafeng** [comment]
这个功能已经实现了，手头上目前没有可用的kafka，建议自行尝试

**Comment by kaitezhan** [comment]
好的，非常感谢！
